version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "8000"
    restart: always

  redis:
    image: redis:6
    env_file:
      - .env
    expose:
      - "6379"
    volumes:
      - redis_volume:/data
    restart: always

volumes:
  redis_volume: